[package]
name = "point_tester"
version = "0.1.0"
authors = ["cora32 <cora32@tuta.io>"]
edition = "2018"

[dependencies]
reqwest = "0.9.20"
serde_derive = "1.0.101"
serde_json = "1.0.40"
uuid = { version = "0.7.4", features = ["serde", "v4"] }
serde = { version = "1.0", features = ["derive"] }